language: python
python:
- '3.6'

before_install:
- openssl aes-256-cbc -K $encrypted_9768f74491f6_key -iv $encrypted_9768f74491f6_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config


deploy:
- echo ${DEPLOY_PORT}
- echo ${DEPLOY_HOST}
- echo ${DEPLOY_USER}
- echo ${DEPLOY_DIRECTORY}
- echo ${TRAVIS_BUILD_DIR}
- provider: script
  skip-cleanup: true
  script: rsync -r --quiet -e 'ssh -p ${DEPLOY_PORT}' --delete-after ${TRAVIS_BUILD_DIR}/* ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: ssh -p ${DEPLOY_PORT} -i /tmp/deploy_rsa ${DEPLOY_USER}@${DEPLOY_HOST} "~/deploy.sh"
  on:
    branch: master
env:
  global:
  - secure: Z1nr+CeuY084ulq7ANEe93DwpD0l88ICdYjvOzVTF2kVTZHn5/7fKhauec7LfIn088XUuGwrRojgA4t+Mc4GPe1Us/c8SrHYrpSczQhen+f6Fbkh6gukEZANGfvsczRkZ+OmO2drcUic+lsJg666bLijSoVatmhTfNb4ZRzZSiSH0PCJGsIgFxq3s3daTFecFQQBpuzJ3J7Mv2jrwoMCBgP1+FXd2Ae4r5yCSsGH1PB/35fT/QrOfHDusbl+4CfIk0rGf3HaGxdWBjOhMTtE1YrgUvMxlGfM26zEZUCuzBX+5zMSkegf5spn0ZWhqEzfP+DjPOncaESdP+i0z2a2LjFEiZXiVUwaL5PnQxr1vAcSd0hZY340bolIoVQU+3+M8hv/fsUq582Iz0ONC9U2iaKXHiceUYxQz68qu/54iuor03SQFYPFxEeefg54D9YHnmGDh4aXhOsun/IVSagaYn/PagdN2dqd+7Ar1JXKDqFowqHSP1eDgq4XeUPyTCKjxIutPtN22TFbvARCW6ggz+rZAwP8/pmJbeSZ4v9G4OB9gsPeZWFjNr0q2LxWSgWw/+DFmtwV/XYrCRITNr0l8RnIGcXqfCrdrcE73daUVn6R82tt0Iu4/kEB/uwVHArEIzkhTPcZvlJMO32tFYW0radQ6b6VCc40LK1iXDkowNc=
  - secure: NEqAf+GMg1q6x/wfOY1hxbskg3VBsBCjGSMZ1rG3o+u5m1QnRE7PMUzmnfs4XtA7cHANm+Z6DUoZbyQG+whOiQFu0vNPGw3ktPKaE2UMtcgDk/2TQ8jsxADL9yPRjzJmgxznJoNGNXzhvcTcZhoWTpMuXOPn1IBfelwTvw0hu29W6xuEpWNkyR+gjiNdLVoQK1eDuOwbbKm1OYDdvopPsFK0OgIq/Z2WwXcP5y+SpSvBLlt17Sirc1ebl5HOXDw55CLPCsgWsEHTiAn/i6Y1koMy2+vvvuR6TL5k17emtgzMC7VyyABfg/gkD8JB37tWzhLWX/QJSicuOjXmQhhLVVN29GpXzw1rutf/GacG+Ksx2y+6pu+skdn7wriRvFsx3k0qXvi9Q6OL6tnW463Q+Jco30419F30FW/h34t4/mtZaHTmX6/yOeeP+vsvpLulJzU9IheMDV10jns6aa2lciFa8bjcfF0FWFu+qZhNzzrKheGyx47CdxcKc8gftj1lQQf6PwiQg+h3jg0prCiyXw1A24I5SlaL03Fpo/irP8UtrZni1LjaWMVJbCdsWdaUe9hZL//9P4kSzr92e+tKfgV5JTJ8Ma1kHJrxmgK9xNV8ZaeCSvdWc397LbW8AbwoIyBFm7WadqpUlAHagUqee7jyqRgK9ts4qR+0UAwXPi8=
  - secure: mN5lhxDQYubLhBJc94BwKz4DOWYcdtpd/lPWUmJK2AO1qS7iW4sC1AhrDUW4K4qnA005iNZeu3MKOwC2Sp0tsPdpdr6cPzl+ptdO40aWDDedEaL6cxuG25I8Uqpn1X5YimyLBD03lRhuo4nJn/GSSKwZx0XlahiziGWxsMxu1mN4LX7XpOasak3hHAYYamMvUNXcJcSP2+xA7OcJ9Sgyh1pumHYt+6HVsnA4aK5Xt1BHlxTIkMEzLJVeqTJK6Gf44X2dbzrtYkqN9IP7qQx7zqLfGuF6z8WSZF7dcgVF9Bec8y/vuUfYjiKbazDR+RBXElpTB1CRkQSmBA+P9HqZfVEl64wakpEYsw1re1Y+4IKhBI2h8nnX2UKqa82Zw6xmoAIZXiG6xWlN1Lddxn1T3srqn0E73IC4fcyO5Lld0tQEBggah+RU6n/erPMfPGh4Gn71GJGyGwi40RoFF/Qi48ZHPf6pTleQMxSVV9tXiXuihAdd+OsAkbb/xu4E0uuJ3/DG8AKiSBpRyxy3VOJYvesGXPphJWpWs5NpKuB6jQB/pDt0wfkEwI69uhJsqS+Zx3m3DUsuCE0DINcCh9FllWfLSAjClIwQQoJ+G6lw3loT7R4q7kDBGCcW9B5llAvpstFXNOGaw6HZTv8SY8U2tIonqZh3qmwX6/8HtrPCB9k=
  - secure: Lmu+qAIzlArS5QevaW9d1X1/sJrhogV19EChYlesHGQ3nO6TwXhJjcqdwVJZdYOLQH7QL3jqU2a3KDWCL4P+gdPz1StQpMrdPwMkFvp4DaWIP/WHY5vRtYeC+/7JvwMHG7hH3WpJLa5IwoFJ10NPJlYcdLT87rqMVgbn9JuqKFBfgQsERxXZVa/08YSr4KjKeBhJ5O+ZGw9GO1HUBcFB4lhxiOIDP8VVRvucGnoV+Y/GC2dvb6FBN4XaStPs1gk9/vU51oAVG2vtgk3tgpOmei0JmwkHbBKegBDJ1cmLsYvwYItD7Xtg/4+eFNFhvy6Mpbkp4rb3O/eDwtEgAWA7fi0mt+f566VHyg/I6LIoEhfMjGt2Tv2kgN8kaFiItxemWLX++fKWfSD3NIdBDh634FJ8OqXcssUu2e1H7DlVbrMydtgiDjuTp0VhoylNmF/TKIYIkxF933OSBHhgHGWORc37g1VP+Ln9vHe/rOeELXFzAxXMqrX0FA+jPbdbX1g4ieoG5gFs8JO6VwtAc1jW91z++qXfpzUx68cMPvgcpybrekIcTgkZ8w8ZflOsLffJ8QMTjPTX42GoXxfSmnr1Y7DOI8DQR+R35WmDw1gkyIP3IKMZDi0LnomfaZqb2AVtpHHY8Yeg6eHaFIFmDP1WV8qGEvViRqvs19T890BK9do=
