language: python
python:
- '3.6'

before_install:
- openssl aes-256-cbc -K $encrypted_9768f74491f6_key -iv $encrypted_9768f74491f6_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script: 
- pytest

deploy:
- provider: script
  skip-cleanup: true
  script: rsync -r --quiet -e 'ssh -p 2560' --delete-after ${TRAVIS_BUILD_DIR}/* ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: ssh -p ${DEPLOY_PORT} -i /tmp/deploy_rsa ${DEPLOY_USER}@${DEPLOY_HOST} "~/deploy.sh"
  on:
    branch: master